# Generated by Django 4.0.4 on 2022-06-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('subtitulo', models.CharField(max_length=80)),
                ('cuerpo', models.CharField(max_length=400)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
    ]
