# Generated by Django 4.0.4 on 2022-06-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.CharField(default='Julián', max_length=20),
            preserve_default=False,
        ),
    ]
